name: Create Release
on:
  push:
    branches:
      - main
      - master
jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: 'Get next minor version'
        uses: paulhatch/semantic-version@v4.0.2
        id: version
        with:
          tag_prefix: "v"
          major_pattern: "(MAJOR-BREAKING-CHANGE)"
          minor_pattern: "(MINOR-NON-BREAKING-CHANGE)"
          format: "v${major}.${minor}.${patch}"
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.version.version.v }}
          generate_release_notes: true
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          GITHUB_REPOSITORY: jptosso/test-actions